sudo: false
language: node_js
node_js:
  - "8.11.1"
before_install: 
  - npm install
cache:
  directories:
    - node_modules
dist: trusty # needs Ubuntu Trusty
sudo: false  # no need for virtualization.
addons:
  chrome: stable # have Travis install chrome stable
script: 
  - npm run gulp
  - npm run build
  - npm run test
after_success:
  - bash <(curl -s https://codecov.io/bash)